// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3zdpyzRQmmxf1oZru4XQbjkAijJiMkW8',
    appId: '1:838764967177:web:e4412ea258e8ef4dbe4fd8',
    messagingSenderId: '838764967177',
    projectId: 'adeiza-new-project',
    authDomain: 'adeiza-new-project.firebaseapp.com',
    storageBucket: 'adeiza-new-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrgnxGUyrSp66vioD-OWXYh2z_jwqJ-I',
    appId: '1:838764967177:android:b766ccbab6298d9ebe4fd8',
    messagingSenderId: '838764967177',
    projectId: 'adeiza-new-project',
    storageBucket: 'adeiza-new-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQ1jjcoFTxvxtMQQPiHQUlsnuJb4eOJs',
    appId: '1:838764967177:ios:d7ed393b27fb14dbbe4fd8',
    messagingSenderId: '838764967177',
    projectId: 'adeiza-new-project',
    storageBucket: 'adeiza-new-project.appspot.com',
    iosClientId: '838764967177-7itk0nqtenma1gurt8svq1hj1s53ih6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQ1jjcoFTxvxtMQQPiHQUlsnuJb4eOJs',
    appId: '1:838764967177:ios:7e448784f423bde7be4fd8',
    messagingSenderId: '838764967177',
    projectId: 'adeiza-new-project',
    storageBucket: 'adeiza-new-project.appspot.com',
    iosClientId: '838764967177-f2v5omn32sbs9vledud36oevaie9se24.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirst.RunnerTests',
  );
}
